// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientDictionaries.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ErrorType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ErrorType
    {
        [EnumMember(Value = "NotFound")]
        NotFound,
        [EnumMember(Value = "Validation")]
        Validation
    }
    internal static class ErrorTypeEnumExtension
    {
        internal static string ToSerializedValue(this ErrorType? value)
        {
            return value == null ? null : ((ErrorType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this ErrorType value)
        {
            switch( value )
            {
                case ErrorType.NotFound:
                    return "NotFound";
                case ErrorType.Validation:
                    return "Validation";
            }
            return null;
        }

        internal static ErrorType? ParseErrorType(this string value)
        {
            switch( value )
            {
                case "NotFound":
                    return ErrorType.NotFound;
                case "Validation":
                    return ErrorType.Validation;
            }
            return null;
        }
    }
}
