// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientDictionaries.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RecordPayloadModel
    {
        /// <summary>
        /// Initializes a new instance of the RecordPayloadModel class.
        /// </summary>
        public RecordPayloadModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RecordPayloadModel class.
        /// </summary>
        public RecordPayloadModel(string payload = default(string))
        {
            Payload = payload;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Payload")]
        public string Payload { get; set; }

    }
}
