// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientDictionaries.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SetRequestModel
    {
        /// <summary>
        /// Initializes a new instance of the SetRequestModel class.
        /// </summary>
        public SetRequestModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SetRequestModel class.
        /// </summary>
        public SetRequestModel(string data = default(string))
        {
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public string Data { get; set; }

    }
}
